version: "3.8"

services:
  db:
    image: postgres
    ports: ["15432:5432"]
    environment:
      - POSTGRES_DB=rasasa
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  redis:
    image: redis
    ports: ["16379:6379"]

