version: "3.8"

services:
  app:
    build: .
    ports: ["8099:8090"]
    profiles: ["local"]
    environment:
     - RASASA_USER=user
     - RASASA_PASS=pass
     - DATABASE_URL=postgres://admin:admin@db:5432/rasasa
     - REDIS_URL=redis://redis:6379
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
  db:
    image: postgres
    ports: ["15432:5432"]
    environment:
      - POSTGRES_DB=rasasa
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  redis:
    image: redis
    ports: ["16379:6379"]

