version: "3.8"

services:
  gateway:
    build: .
    ports: ["8090:8090"]
    profiles: ["local"]
    command: "./rasasa-gateway"
    environment:
     - RASASA_USER=user
     - RASASA_PASS=pass
     - REDIS_URL=redis://redis:6379
     - SERVER_URL=http://server:8091
     - READ_URL=http://read-server:8092
    links:
      - server
      - read-server
      - redis
    depends_on:
      - server
      - read-server
      - redis
  server:
    build: .
    profiles: ["local"]
    command: "./rasasa-server"
    environment:
     - SERVER_URL=http://0.0.0.0:8091
     - DATABASE_URL=postgres://postgres:postgres@db:5432/rasasa
    links:
      - db
    depends_on:
      - db
  read-server:
    build: .
    profiles: ["local"]
    command: "sh -c 'pnpm start | pnpx pino-pretty -S'"
    working_dir: "/home/runner/app/read-server"
    environment:
     - READ_URL=http://0.0.0.0:8092
     - REDIS_URL=redis://redis:6379
    links:
      - redis
    depends_on:
      - redis
  db:
    image: postgres
    ports: ["15432:5432"]
    environment:
      - POSTGRES_DB=rasasa
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis
    ports: ["16379:6379"]

