#!/usr/bin/env bash
cd "$(dirname "$0")" || exit
source scripts/runner.sh

task_server:build() {
  cd server || return
  cargo build --release
}

task_server:watch() {
  runner_parallel server:watch:check server:watch:run
}

task_server:watch:check() {
  cd server || return
  touch .watchtrigger
  cargo watch -x check -s 'touch .watchtrigger'
}

task_server:watch:run() {
  cd server || return
  cargo watch --no-gitignore -w .watchtrigger -x run
}
