[package]
name = "rasasa-server"
version = "0.1.0"
authors = ["Tim Deve <timdeve@users.noreply.github.com>"]
edition = "2018"

[dependencies]
rss       = "1.6.1"
tokio     = "0.1.16"
serde     = "1.0.89"
tower-web = "0.3.5"

