name: Docker Image

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1

    - uses: actions/cache@v1
      name: Cache Docker
      with:
        path: /var/lib/docker
        key: ${{ runner.os }}-rust-${{ env.GITHUB_SHA }}
        restore-keys: ${{ runner.os }}-docker-

    - name: Record build time
      run: date +%s > time

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/timdeve/rasasa/rasasa:$(cat time)

    - name: Push the image to GPR
      run: |
        docker login docker.pkg.github.com -u TimDeve -p "${GITHUB_PACKAGE_REGISTRY_TOKEN}"
        docker push docker.pkg.github.com/timdeve/rasasa/rasasa:$(cat time)
      env:
        GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}
