name: Docker Image

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1

    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true

    - name: Record build time
      run: date +%s > time

    - name: Build the Docker image
      run: docker build . -t ghcr.io/timdeve/rasasa/rasasa:$(cat time) -t ghcr.io/timdeve/rasasa/rasasa:latest

    - name: Push the image to GPR
      if: github.ref == 'refs/heads/master'
      run: |
        echo $GITHUB_PACKAGE_REGISTRY_TOKEN | docker login ghcr.io -u TimDeve --password-stdin
        docker push ghcr.io/timdeve/rasasa/rasasa
      env:
        GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}
