name: Docker Image

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1

    - uses: actions/cache@v1
      name: Cache Docker
      with:
        path: /var/lib/docker
        key: ${{ runner.os }}-docker-${{ env.GITHUB_SHA }}
        restore-keys: ${{ runner.os }}-docker-

    - name: Record build time
      run: date +%s > time

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/timdeve/rasasa/rasasa:$(cat time)

    - name: Push the image to GPR
      run: |
        echo $GITHUB_PACKAGE_REGISTRY_TOKEN | docker login ghcr.io -u TimDeve --password-stdin
        docker push ghcr.io/timdeve/rasasa/rasasa:$(cat time)
      env:
        GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}
